import { Session } from "@/lib/types"

export const sessions: Session[] = [
  {
    id: "registration",
    time: "08:30 - 09:00",
    title: "Registration & Welcome Coffee",
    speaker: "Organizers",
    description: "Check-in, grab your badge, and network over coffee.",
  },
  {
    id: "keynote",
    time: "09:00 - 09:45",
    title: "Opening Keynote: The Future of SAP Development",
    speaker: "Dr. Sarah Martinez",
    speakerId: "speaker-1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam rem aperiam. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
  },
  {
    id: "session1",
    time: "10:00 - 10:45",
    title: "Building Scalable Apps with SAP BTP",
    speaker: "James Wilson",
    speakerId: "speaker-4",
    description: "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum. Nam libero tempore cum soluta nobis est eligendi optio cumque nihil impedit. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates. Itaque earum rerum hic tenetur a sapiente delectus ut aut reiciendis voluptatibus maiores.",
  },
  {
    id: "break1",
    time: "10:45 - 11:00",
    title: "Coffee Break",
    speaker: "Networking",
    description: "Short break to recharge and connect with fellow attendees.",
  },
  {
    id: "session2",
    time: "11:00 - 11:45",
    title: "SAP CAP: From Zero to Production",
    speaker: "Anna Kowalski",
    speakerId: "speaker-5",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit sed quia consequuntur. Ut enim ad minima veniam quis nostrum exercitationem ullam corporis suscipit laboriosam nisi ut aliquid. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae. At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium. Temporibus autem quibusdam et aut officiis debitis rerum necessitatibus saepe eveniet voluptates repudiandae.",
  },
  {
    id: "session3",
    time: "12:00 - 12:45",
    title: "AI & Machine Learning in SAP Ecosystems",
    speaker: "Emma Rodriguez",
    speakerId: "speaker-7",
    description: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit sed consequuntur magni. Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt labore. Ut enim ad minima veniam quis nostrum exercitationem ullam corporis suscipit laboriosam ut aliquid. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat pariatur.",
  },
  {
    id: "lunch",
    time: "12:45 - 14:00",
    title: "Lunch & Networking",
    speaker: "Everyone",
    description: "Enjoy a catered lunch and connect with speakers and attendees.",
  },
  {
    id: "session4",
    time: "14:00 - 14:45",
    title: "Modern UI Development with SAPUI5 & Fiori",
    speaker: "Lisa Hoffmann",
    speakerId: "speaker-3",
    description: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur. Nam libero tempore cum soluta nobis est eligendi optio cumque nihil impedit quo minus id. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet voluptates. Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit sed quia.",
  },
  {
    id: "session5",
    time: "15:00 - 15:45",
    title: "DevOps & CI/CD for SAP Projects",
    speaker: "Thomas Bauer",
    speakerId: "speaker-8",
    description: "Itaque earum rerum hic tenetur a sapiente delectus ut aut reiciendis voluptatibus maiores alias. Ut enim ad minima veniam quis nostrum exercitationem ullam corporis suscipit laboriosam nisi aliquid. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium totam. Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla. Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim.",
  },
  {
    id: "break2",
    time: "15:45 - 16:00",
    title: "Afternoon Break",
    speaker: "Networking",
    description: "Final coffee break before closing sessions.",
  },
  {
    id: "panel",
    time: "16:00 - 17:00",
    title: "Panel Discussion: SAP Community & Open Source",
    speaker: "Multiple Speakers",
    speakerId: ["speaker-1", "speaker-2", "speaker-6"],
    description: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit sed quia consequuntur. At vero eos et accusamus et iusto odio dignissimos ducimus blanditiis praesentium voluptatum deleniti. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut voluptates. Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
  },
  {
    id: "closing",
    time: "17:00 - 17:30",
    title: "Closing Remarks & Raffle",
    speaker: "Organizers",
    description: "Wrap-up, raffle prizes, and see you next year!",
  },
]
